name: 'Hello World'
description: 'Greet someone'
inputs:
  CERT_SUBJ: 
    description: Public Cert Subject
    required: true
runs:
  using: 'docker'
  image: docker://public.ecr.aws/n8p1g0n4/kivera-proxy:latest
  env:
    CERT_SUBJ: ${{ inputs.CERT_SUBJ }}
