name: 'Run Kivera'
description: 'Start Kivera Proxy'
inputs:
  KIVERA_CREDENTIALS: 
    description: Kivera Credentials
    required: true
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/run.sh
      shell: bash    
# runs:
#   using: 'docker'
#   image: docker://public.ecr.aws/n8p1g0n4/kivera-proxy:latest
#   env:
#     KIVERA_CREDENTIALS: ${{ inputs.KIVERA_CREDENTIALS }}